### ISSUE TITLE
Does not build with ghc 9.2.1

### ISSUE THREAD

**Issue by emberdart** [dylex/invertible#5]
Maybe something to do with TH changing subtly on 9.2.1?

```
Data/Invertible/TH.hs:65:11: error:
    • The constructor ‘TH.ConP’ should have 3 arguments, but has been given 2
    • In the pattern: TH.ConP c a
      In an equation for ‘patToExp’:
          patToExp (TH.ConP c a)
            = foldl (\ f -> TH.AppE f . patToExp) (TH.ConE c) a
   |
65 | patToExp (TH.ConP c a) = foldl (\f -> TH.AppE f . patToExp) (TH.ConE c) a
```

**Comment by avanov** [comment]
@dylex I tested your [fix](https://github.com/dylex/invertible/commit/e203c6a729fde87b1f903c3f468f739a085fb446) on GHC 9.4.4 in the context of `web-inv-route` and I confirm it works. I would appreciate that commit on Hackage.

**Comment by dylex** [comment]
Thanks, 0.2.0.8 released with fix

**Comment by avanov** [comment]
Thank you!
